<div class="longtext">
<p>Grâce à la motivation de HANG Xingchen qui était le président de l'Association des anciens élèves de NJU, et SHI Jianjun qui était le vice-président de l'Association des anciens élèves de NJU, l'Association des anciens élèves de l'Université de Nanjing en France a été étabie depuis 2003. Dr. JI Hong, ancien étudiant du Département de physique de l'Université de Nanjing et Professeur JIA Xiaoping ont conduit la Comité préparatoire d'établissement de l' Association des anciens élèves de NJU. Par la communication et la consultation avec la majorité des étudiants de NJU en France, et enfin en 2004, le 20 Avril, la comité a convoqué la réunion d'établissement de l'Association des anciens élèves de NJU en France à St. Georgea.</p><br/>

<p>La France a établi le nom français de la réunion de l'Association des anciens est AAENF (Association des Anciens Elèves de NJU en France), d'accord sur une constitution et construit à cet effet l'Association des anciens français, et a élu et nommé par le Dr saison Association des anciens de l'Université de Nanjing rouge France professeur Gu Xiaoping, Association vice-président de Nanjing anciens de l'Université en France, tandis que les feuilles de souvenirs nommé secrétaire, les candidats membres trésorier et du conseil, charte des anciens et des résolutions du Conseil sont transmis à l'agence du gouvernement français après la réunion officiellement enregistrée, et en France a publié un journal Nanjing public Association des anciens de l'Université a été fondée en France Shen Ming.</p><br/>

<p>Conseil Nanjing anciens de l'Université dans le but de la France est respecter sincèrement Puxiong Wei, une centaine d'années devise Reigaku ligne sud de Londres, afin de réunir la majorité de l'Université de Nanjing en France en Europe la responsabilité des bottes de voyage, pour renforcer les contacts inter-anciens entre les anciens et alma mater, et réaliser activement la culture , la recherche scientifique, les activités d'échanges universitaires et de la vie, afin de promouvoir la coopération économique et culturelle et éducative entre la Chine et la France, l'Europe centrale et les efforts pour le développement rapide de son alma mater, de contribuer à la prospérité de la patrie.</p><br/>
<p>Aujourd'hui, l'Association Nanjing anciens de l'Université en France après huit années de développement et de croissance, les membres du commerce en France et en Europe de l'Ouest, les communications, les technologies de l'information, la banque, la finance, l'éducation, l'énergie, l'industrie, l'automobile traditionnelle, la construction, l'équipement médical, la culture, la recherche scientifique et les services gouvernementaux et d'autres domaines.</p><br/>
<p>France Université de Nanjing, l'Association des anciens de l'Université de Nanjing a reçu le secrétaire du Parti de Hong Yinxing, secrétaire adjoint GUO Guang-argent, président de l'Université de Nanjing Jiang Shusheng, Chen Jun, Nanjing University Symphony Orchestra, le vice-président de l'Association Nanjing anciens de l'Université Gao Peng, l'Université de Nanjing EMBA Visite d'étude de la délégation en Europe la visite de la délégation en Europe tels que l'Université de Nanjing, son alma mater et le leadership organisé et restent une interaction active de sous-droit, a reçu une cote élevée.</p><br/>
<p>2010 a été décerné l'Académie française des Arts a organisé un « Young Artist Award pour l'encouragement, » le département des anciens NTU Jiang Bin « Ecotopia » exposition d'œuvres des réalisations. 2012 organisé par l'Institut de l'Université de Nankin lauréat de l'Académie des anciens français Francois Cheng vieil homme « du langage poétique occidentale situation de l'Est, » l'appréciation de la poésie française sera. Et puis dans les participants amis sino-français ont obtenu une excellente réponse, les anciens riches activités de loisirs, et de promouvoir les échanges culturels sino-français et la reconnaissance basée sur le bien également élargi l'Université de Nanjing de visibilité.
</p>
</div>